import google, re, urllib2
from bs4 import BeautifulSoup

def getPages(query):
	"""
	Input: A string representing a search query. (the question)
	Returns: A list of urls generated by the search query
	"""
	pages = google.search(query,start=0,stop=10)
	page_list = []
	for page in pages:
		page_list.append(page)
	return page_list

def makeSoup(page):
	"""
	Input: A link to a webpage
	Output: Actual text from the webpage
	"""
	try:	
		url = urllib2.urlopen(page)
		html = url.read().decode('utf-8')
		soup = BeautifulSoup(html, 'html.parser')
		raw = soup.get_text()
		text = re.sub("[\t\n ]+",' ',raw)
	except:
		return ""
	return text

def getNames(text):
	"""
	Input: Text to find names from
	Output: Dic of names and their frequencies
	"""
	dic = {}
	pattern = "[A-Z][a-z]+ [A-Z][a-z]+"
	result = re.findall(pattern,text)
	for name in result:
		if name not in dic:
			dic[name] = 0;
		dic[name] += 1;
	return dic

def findName(dic):
	"""
	Input: Dictionary to find name from
	Output: Most frequent name
	"""
	maxF = 0
	maxN = ""
	for name in dic.keys():
		if dic[name]>maxF:
			maxF = dic[name]
			maxN = name
	return maxN

def answer(query):
	"""
	Input: String query
	Output: answer
	"""
	totalText = ""
	page_list = getPages(query)
	for page in page_list:
		totalText += makeSoup(page)
	dic = getNames(totalText)
	return findName(dic)

print answer("Who played spiderman?")